site_name: "DECADE-X Standards"
site_url: "https://shibukawa310.github.io/dx_standards/"

theme:
  name: material

# --- AJOUT DU DOSSIER D'INCLUSION ---
plugins:
  - search
  - macros:
      include_dir: includes  # On dit au plugin de regarder ici

extra_css:
  - assets/custom.css

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.superfences
