[project]
site_name = "DECADE-X Standards"
site_url = "https://shibukawa310.github.io/dx_standards/"

[project.theme]
name = "material"

# J'ai retiré le [project.nav] exprès. Zensical va scanner "docs/" tout seul.
# J'ai aussi retiré les extensions Markdown temporairement.
